// This file is @generated by prost-build.
#[derive(serde::Deserialize, serde::Serialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StarkVrfRequest {
    #[prost(string, repeated, tag = "1")]
    pub felt252_seed: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Deserialize, serde::Serialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StarkVrfProof {
    #[prost(string, tag = "1")]
    pub felt252_gamma_x: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub felt252_gamma_y: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub felt252_c: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub felt252_s: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub felt252_sqrt_ratio: ::prost::alloc::string::String,
}
